backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img
site_url: https://cofounderscompass.com
display_url: https://cofounderscompass.com
publish_mode: editorial_workflow
logo_url: https://cofounderscompass.com/img/logo.svg

collections:
  - name: "articles"
    label: "Articles"
    label_singular: "Article"
    folder: "src/pages/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "article-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Subtitle, name: subtitle, widget: string },
                ],
            }

      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Intro Title", name: "introTitle", widget: "string" }
          - { label: "Intro Text", name: "introText", widget: "markdown" }
          - {
              label: About Image,
              name: aboutImage,
              widget: object,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Alt, name: alt, widget: string },
                ],
            }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "configs"
    label: "Configurations"
    files:
      - file: "src/configs/navigation.yml"
        label: "Navigation"
        name: "navigation"
        fields:
          - {
              label: "Template Key",
              name: templateKey,
              widget: hidden,
              default: navigation,
            }
          - {
              label: "Links",
              name: "links",
              widget: list,
              fields:
                [
                  { label: Text, name: text, widget: string },
                  { label: Path, name: path, widget: string },
                  {
                    label: Show in Header,
                    name: showInHeader,
                    widget: boolean,
                    default: true,
                  },
                  {
                    label: Show in Footer,
                    name: showInFooter,
                    widget: boolean,
                    default: true,
                  },
                  {
                    label: Use External Link,
                    name: useExternalLink,
                    widget: boolean,
                    default: false,
                  },
                ],
            }
